version: '3.8'

services:
  php:
    image: php:8.0-fpm
    volumes:
      - ./code:/var/www/html
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
    depends_on:
      - composer

  composer:
    image: composer:latest
    volumes:
      - ./code:/app
