version: '3.8'
services:
    php:
        build:
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html
    nginx:
        image: nginx:latest
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "9090:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306

volumes:
    mysql_data:
